# Generated by Django 5.2.2 on 2025-06-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
