# Generated by Django 5.2.2 on 2025-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='num',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
