# Generated by Django 5.2.2 on 2025-06-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_num'),
        ('denisshop', '0002_alter_genre_options_alter_key_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='games',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='num',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='cart',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='denisshop.game', verbose_name='Игры'),
            preserve_default=False,
        ),
    ]
