# Generated by Django 5.2.2 on 2025-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'verbose_name': 'Ключ', 'verbose_name_plural': 'Ключи'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Платформа', 'verbose_name_plural': 'Платформы'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
