# Generated by Django 5.2.2 on 2025-06-19 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0002_alter_genre_options_alter_key_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='denisshop.game', verbose_name='Игра'),
        ),
    ]
