# Generated by Django 5.2.2 on 2025-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='slug',
            field=models.SlugField(blank=True, default='1', max_length=64),
        ),
    ]
