# Generated by Django 5.2.2 on 2025-06-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0005_key_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='key',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
