# Generated by Django 5.2.2 on 2025-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0006_remove_review_user_alter_key_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='game_images', verbose_name='Изображение'),
        ),
    ]
