# Generated by Django 5.2.2 on 2025-06-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0007_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='denisshop.key'),
        ),
    ]
