# Generated by Django 5.2.2 on 2025-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0008_alter_review_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='game_images', verbose_name='Изображение'),
        ),
    ]
