# Generated by Django 5.2.2 on 2025-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisshop', '0009_alter_review_options_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2000-1-1 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
